@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/auth
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json

### signUp
POST {{url}}/signUp {{protocol}}
Content-Type: {{contentTypeJson}}

{
"name": "name10",
"email": "name12@company.com",
"password": "123456",
"isAdmin": true,
"roles": ["ADMIN"]
}

### signIn as a regular user
POST {{url}}/signIn {{protocol}}
Content-Type: {{contentTypeJson}}

{
"email": "name9@company.com",
"password": "123456"
}

### signIn as admin user
POST {{url}}/signIn {{protocol}}
Content-Type: {{contentTypeJson}}

{
"email": "admin@company.com",
"password": "123456"
}

### signOut
GET {{url}}/signOut {{protocol}}
Content-Type: {{contentTypeJson}}
