@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/auth
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json

### signUp
POST {{url}}/signUp {{protocol}}
Content-Type: {{contentTypeJson}}

{
"name": "jdoe",
"email": "jdoe1@company.com",
"password": "123456",
"isAdmin": false
}

### signIn
POST {{url}}/signIn {{protocol}}
Content-Type: {{contentTypeJson}}

{
"email": "admin@company.com",
"password": "123456"
}

### signOut
GET {{url}}/signOut {{protocol}}
Content-Type: {{contentTypeJson}}
