@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/fileuploads
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@entityId = 5fc0d3445e53d7734973b1bc
@authHeader = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjlhOTc0NGUwN2M5NzM5MWM0OWM2NTYiLCJpYXQiOjE2MDY0ODM5NjgsImV4cCI6MTYwNjUxMjc2OH0.40rXkTe1k8YmH3XHq_DUHOhEXSF-KuWHOH2O30ixYOk

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

{
    "name": "test fileupload"
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}