@protocol = HTTP/1.1
@host = http://localhost
@port = 3000
@baseUrl = /v1/api/products
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@entityId = 5f9454940a1c224ee1780bc3
@authCookie = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjgwMjcyYWRhYjU2YzdhOTExMDY0YzAiLCJpYXQiOjE2MDIyMzkxNTgsImV4cCI6MTYwMjI2Nzk1OH0.pKJyR-RoURTQ2D1T7NfdWpfiAcbPFRbqf8RpY6dA9KA

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findById
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}

{
    "name": "Airpods Wireless Bluetooth Headphones",
    "image": "/images/airpods.jpg",
    "description":
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    "brand": "Apple",
    "category": "Electronics",
    "price": 89.99,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
    "user": "5f945f70afd720514fdf0bfc"
  }

### updateById
PATCH {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}

{
"name": "name updated",
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}
