@protocol = HTTP/1.1
@host = http://localhost
@port = 3000
@baseUrl = /v1/api/tasks
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@entityId = 5f803bb658fc028393315ca5
@authCookie = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjgwMjcyYWRhYjU2YzdhOTExMDY0YzAiLCJpYXQiOjE2MDIyMzkxNTgsImV4cCI6MTYwMjI2Nzk1OH0.pKJyR-RoURTQ2D1T7NfdWpfiAcbPFRbqf8RpY6dA9KA

### head
HEAD {{url}} {{protocol}}

### head
HEAD {{url}}/{{entityId}} {{protocol}}

### options
OPTIONS {{url}} {{protocol}}

### options
OPTIONS {{url}}/{{entityId}} {{protocol}}

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findAll with page request options
GET {{url}}?assignee=assignee2&isCompleted=true&page=1&pageLimit=10&sort=-isCompleted name -assignee {{protocol}}
Content-Type: {{contentTypeJson}}

### findById
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}

{
"name": "task3"
}

# {
# "name": "task7",
# "assignee": "name3",
# "dueDateStr": "2020-10-02T14:26:17.101Z",
# "projects": ["pr1", "pr2", "pr3"],
# "description": "description",
# "isCompleted": true,
# "comments": ["comment1", "comment2"],
# "responsibles": [
# "5f802712dab56c7a911064be",
# "5f80272adab56c7a911064c0"
# ]
# }

### updateById
PATCH {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}

{
"name": "task_changed1"
}

### replaceById
PUT {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}

{
"name": "name_changed"
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}
