@protocol = HTTP/1.1
@host = http://localhost
@port = 3000
@baseUrl = /v1/api/users
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@entityId = 5f9454940a1c224ee1780bc3

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findById
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

{
"name": "jdoe1",
"email": "jdoe1@company.com",
"password": "12345678",
"isAdmin": false
}

### updateById
PATCH {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

{
"name": "jsmith"
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
